runtime: python311

# Configuraci칩n de instancia
instance_class: F2

# Escalado autom치tico
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Variables de entorno
env_variables:
  FLASK_ENV: "production"
  FLASK_APP: "app:app"

# Manejo de archivos est치ticos
handlers:
  - url: /static
    static_dir: static
    secure: always
    expiration: "7d"
    
  - url: /favicon\.ico
    static_files: static/favicon.ico
    upload: static/favicon\.ico
    secure: always
    
  - url: /.*
    script: auto
    secure: always

# Servicios entrantes
inbound_services:
  - warmup

# Configuraci칩n de recursos
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10