# ✅ CONFIGURACIÓN PARA APP.PY FLASK EXISTENTE
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

# ✅ VARIABLES DE SUSTITUCIÓN
substitutions:
  _SERVICE_NAME: 'ava-app'
  _REGION: 'us-central1'
  _MEMORY: '4Gi'
  _CPU: '2'
  _TIMEOUT: '3600s'
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '1'

steps:
  # ✅ BUILD
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '.'

  # ✅ PUSH
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'

  # ✅ DEPLOY
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=${_MEMORY}'
      - '--cpu=${_CPU}'
      - '--timeout=${_TIMEOUT}'
      - '--port=8080'
      - '--max-instances=${_MAX_INSTANCES}'
      - '--min-instances=${_MIN_INSTANCES}'

timeout: '2400s'