# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ava_bot.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ava_bot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rava_bot.proto\x12\x07\x61va_bot\"\x0f\n\rHealthRequest\"w\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x01\x12\x13\n\x0btotal_tools\x18\x04 \x01(\x05\x12\x15\n\rrequest_count\x18\x05 \x01(\x05\"\x0e\n\x0cToolsRequest\"\xf1\x01\n\tToolsList\x12,\n\x05tools\x18\x01 \x03(\x0b\x32\x1d.ava_bot.ToolsList.ToolsEntry\x12\x30\n\x07schemas\x18\x02 \x03(\x0b\x32\x1f.ava_bot.ToolsList.SchemasEntry\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x1a,\n\nToolsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cSchemasEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"4\n\x0bToolRequest\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x12\n\nparameters\x18\x02 \x01(\t\"g\n\x0cToolResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nraw_result\x18\x03 \x01(\t\x12\x11\n\ttool_name\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t2\xb7\x01\n\x06\x41vaBot\x12\x39\n\x06Health\x12\x16.ava_bot.HealthRequest\x1a\x17.ava_bot.HealthResponse\x12\x36\n\tListTools\x12\x15.ava_bot.ToolsRequest\x1a\x12.ava_bot.ToolsList\x12:\n\x0b\x45xecuteTool\x12\x14.ava_bot.ToolRequest\x1a\x15.ava_bot.ToolResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ava_bot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOOLSLIST_TOOLSENTRY']._loaded_options = None
  _globals['_TOOLSLIST_TOOLSENTRY']._serialized_options = b'8\001'
  _globals['_TOOLSLIST_SCHEMASENTRY']._loaded_options = None
  _globals['_TOOLSLIST_SCHEMASENTRY']._serialized_options = b'8\001'
  _globals['_HEALTHREQUEST']._serialized_start=26
  _globals['_HEALTHREQUEST']._serialized_end=41
  _globals['_HEALTHRESPONSE']._serialized_start=43
  _globals['_HEALTHRESPONSE']._serialized_end=162
  _globals['_TOOLSREQUEST']._serialized_start=164
  _globals['_TOOLSREQUEST']._serialized_end=178
  _globals['_TOOLSLIST']._serialized_start=181
  _globals['_TOOLSLIST']._serialized_end=422
  _globals['_TOOLSLIST_TOOLSENTRY']._serialized_start=330
  _globals['_TOOLSLIST_TOOLSENTRY']._serialized_end=374
  _globals['_TOOLSLIST_SCHEMASENTRY']._serialized_start=376
  _globals['_TOOLSLIST_SCHEMASENTRY']._serialized_end=422
  _globals['_TOOLREQUEST']._serialized_start=424
  _globals['_TOOLREQUEST']._serialized_end=476
  _globals['_TOOLRESPONSE']._serialized_start=478
  _globals['_TOOLRESPONSE']._serialized_end=581
  _globals['_AVABOT']._serialized_start=584
  _globals['_AVABOT']._serialized_end=767
# @@protoc_insertion_point(module_scope)
